name: Pre-release and release to QA

on:
  workflow_call:
  push:
    branches:
      - release-qa

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-qa:
    name: Tag Release for QA
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get-release-version.outputs.version-name	 }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: release-qa
          fetch-depth: 0

      - uses: wemogy/get-release-version-action@v4.3.2
        id: get-release-version
        with:
          prefix: "v"
          suffix: "qa"
          bumping-suffix: "hotfix"
          create-tag: "true"
          git-username: "jtl"
          git-email: "npm@jtl-cloud.com"
          
          mode: "semantic"
      - name: Check if secret is empty
        run: |
          if [ -z "${{ secrets.TEST_SECRET }}" ]; then
            echo "TEST_SECRET is empty or not set"
            exit 1  # Fail the step (optional)
          else
            echo "TEST_SECRET is set (but value is hidden for security)"
          fi

  build:
    name: Build for QA
    runs-on: ubuntu-22.04
    needs: [tag-qa]
    steps:
     - run: echo ${{ secrets.TEST_SECRET }}

  release:
    name: Release for QA
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
     - run: echo Release